server.http.use-x-forwarded = true

[server.listener]
https.bind = "[::]:10003"
https.protocol = "http"
https.tls.implicit = true
imaps.bind = "[::]:993"
imaps.protocol = "imap"
imaps.tls.implicit = true
sieve.bind = "[::]:4190"
sieve.protocol = "managesieve"
smtp.bind = "[::]:25"
smtp.protocol = "smtp"
submissions.bind = "[::]:465"
submissions.protocol = "smtp"
submissions.tls.implicit = true

[storage]
data = "rocksdb"
fts = "rocksdb"
blob = "rocksdb"
lookup = "rocksdb"
directory = "internal"

[store."rocksdb"]
type = "rocksdb"
path = "/opt/stalwart-mail/data"
compression = "lz4"

[tracer."stdout"]
type = "stdout"
level = "info"
ansi = false
enable = true

[lookup.nextcloud-aio]
domain = "%{env:MAIL_DOMAIN}%"
hostname = "mail.%{env:MAIL_DOMAIN}%"

[certificate.nextcloud-aio]
cert = "%{file:/opt/aio-certs/fullchain.crt}%"
default = true
private-key = "%{file:/opt/aio-certs/privkey.key}%"

[authentication.fallback-admin]
user = "admin"
secret = "%{env:ADMIN_SECRET}%"
